# Generated by Django 5.0.7 on 2024-07-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='CreatedUser',
            field=models.CharField(max_length=255),
        ),
    ]
